apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: php-scheduler
              image: laravel-app-php
              command: ["php", "artisan", "schedule:run"]
              envFrom:
                - secretRef:
                    name: laravelapp-secret
          restartPolicy: OnFailure
